<?php
/**
 *
 */
function fbrate_permission() {
  return array(
    'Use import post form' => array(
      'title' => 'Use import post form', 
      'description' => 'Use import post form', 
    ), 
    'Connect with Facebook' => array(
      'title' => 'Connect with Facebook', 
      'description' => 'Connect with Facebook', 
    ), 
    'Read Post Comments' => array(
      'title' => 'Read Post Comments', 
      'description' => 'Read Post Comments', 
    ), 
  );
}
